# Generated by Django 3.1 on 2023-11-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_remove_domain_user'),
        ('accounts', '0003_auto_20231101_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='domains',
            field=models.ManyToManyField(to='domain.Domain'),
        ),
    ]
