# Generated by Django 3.1 on 2023-11-03 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_domains'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='domains',
        ),
    ]
