# Generated by Django 3.1 on 2023-11-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='recommended',
            field=models.CharField(choices=[('recommended', 'Recommended'), ('registration', 'Registration')], default='registration', max_length=12),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German')], default='en', max_length=2, verbose_name='Language'),
        ),
    ]
