# Generated by Django 3.1 on 2023-11-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
        ('accounts', '0006_auto_20231112_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='recommended_user',
            field=models.ManyToManyField(blank=True, to='recommendation.Recommendation'),
        ),
    ]
