# Generated by Django 3.1 on 2023-10-31 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geotargeting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShortcodeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_destination', models.CharField(max_length=520)),
                ('url_titel', models.CharField(blank=True, max_length=125)),
                ('url_source', models.CharField(blank=True, max_length=525)),
                ('url_medium', models.CharField(blank=True, max_length=525)),
                ('url_campaign', models.CharField(blank=True, max_length=525)),
                ('url_term', models.CharField(blank=True, max_length=525)),
                ('url_content', models.CharField(blank=True, max_length=525)),
                ('url_create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('url_archivate', models.BooleanField(default=False)),
                ('url_active', models.BooleanField(default=True)),
                ('favicon_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('button_label', models.CharField(blank=True, max_length=520, null=True)),
                ('shortcode', models.CharField(blank=True, max_length=15, unique=True)),
                ('limitation_active', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('alternative_url', models.URLField(blank=True, null=True)),
                ('geo_targeting_on_off', models.BooleanField(default=False)),
                ('link_geo', models.CharField(blank=True, max_length=320, null=True)),
                ('android_on_off', models.BooleanField(default=False)),
                ('android', models.CharField(blank=True, max_length=320, null=True)),
                ('ios_on_off', models.BooleanField(default=False)),
                ('ios', models.CharField(blank=True, max_length=320, null=True)),
                ('tags', models.ManyToManyField(related_name='shortcodes', to='shortcode.Tag')),
                ('template_geo', models.ManyToManyField(related_name='geothemplate', to='geotargeting.GeoThemplate')),
                ('url_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
