# Generated by Django 3.1 on 2023-11-02 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkinbio', '0002_auto_20231101_1629'),
        ('shortcode', '0003_shortcodeclass_linkinbiopage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcodeclass',
            name='linkinbiopage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='linkinbio.linkinbio'),
        ),
    ]
