# Generated by Django 3.1 on 2023-11-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0006_auto_20231103_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
