# Generated by Django 3.2 on 2023-10-31 12:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subline', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('headline', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('og_description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketingField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='marketing_images/')),
                ('headline', models.CharField(max_length=200, verbose_name='headline')),
                ('subline', models.CharField(max_length=200, verbose_name='subline')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='text')),
                ('content_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentpages.contentpage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
