# Generated by Django 3.1 on 2023-11-11 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0006_auto_20231103_1243'),
        ('linkinbio', '0002_auto_20231101_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkinbio',
            name='shortcode',
            field=models.ForeignKey(default=86, on_delete=django.db.models.deletion.CASCADE, to='shortcode.shortcodeclass'),
            preserve_default=False,
        ),
    ]
