# Generated by Django 3.1 on 2023-11-11 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortcode', '0006_auto_20231103_1243'),
        ('linkinbio', '0003_linkinbio_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkinbio',
            name='shortcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shortcode.shortcodeclass'),
        ),
    ]
