# Generated by Django 3.1 on 2023-11-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkinbio', '0004_auto_20231111_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkinbiolink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
